### ISSUE TITLE
Improve handling of PyiCloudAPIResponseError and reduce sleep interval

### ISSUE THREAD

**Issue by airwinb** [airwinb/iCloudLocationFetcher#27]
The retry interval should be decreased from 1800 s to a few minutes in case of a PyiCloudAPIResponseError

```
2017-11-13 02:05:50,838 ERROR     (450)
2017-11-13 02:05:50,840 ERROR    Connection error or PyiCloud exception
Traceback (most recent call last):
  File "iCloudLocationFetcher.py", line 310, in main
    location = apple_device.location()
  File "/home/erwin/iCloudLocationFetcher/pyicloud/services/findmyiphone.py", line 112, in location
    self.manager.refresh_client()
  File "/home/erwin/iCloudLocationFetcher/pyicloud/services/findmyiphone.py", line 44, in refresh_client
    'selectedDevice': 'all',
  File "/home/erwin/virtualenv/pyicloud/local/lib/python2.7/site-packages/requests-2.18.4-py2.7.egg/requests/sessions.py", line 555, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/erwin/iCloudLocationFetcher/pyicloud/base.py", line 74, in request
    self._raise_error(response.status_code, response.reason)
  File "/home/erwin/iCloudLocationFetcher/pyicloud/base.py", line 122, in _raise_error
    raise api_error
PyiCloudAPIResponseError:  (450)
```

**Comment by airwinb** [comment]
Done
